### ISSUE TITLE
Meet some problems related to nvdiffrast when exporting meshes

### ISSUE THREAD

**Issue by snowflakewang** [deepseek-ai/DreamCraft3D#28]
Hello, thank you for your brilliant work! I am running some cases based on your code. The first 3 stages (NeuS & NeRF, Geometry, and Texture) went well. But when exporting meshes, I meet the problem:
```bash
[F glutil.cpp:338] eglInitialize() failed
```
Seems that it is related to nvdiffrast. I tried some solutions from the Internet but they did not work. In the .yaml file:
```yaml
renderer_type: "nvdiff-rasterizer"
renderer:
    context_type: cuda
```
So I have used _dr.RasterizeCudaContext_ instead of _dr.RasterizeGLContext_.

Looking forward to your reply, thanks a lot :)
